compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: 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

yarnPath: .yarn/releases/yarn-4.9.1.cjs
