compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: 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

yarnPath: .yarn/releases/yarn-4.9.1.cjs
