name: CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test:unit --ci --coverage

      - name: Build
        run: yarn build

      - name: E2E tests
        run: yarn test:e2e --forceExit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
    env:
      CI: true
