name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pack-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack build
        run: echo "pack_name=$(npm pack | tail -n 1)" >> $GITHUB_ENV

      - name: Pack tests
        run: |
          cp ./${{ env.pack_name }} ./test-publish
          cd ./test-publish
          npm install ./${{ env.pack_name }}

    env:
      CI: true

  unit-tests:
    runs-on: ubuntu-latest
    needs: [pack-tests]
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Unit tests
        run: npm run test -- --ci --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
    env:
      CI: true

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [pack-tests]
    strategy:
      matrix:
        browser: [chrome, firefox]
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
          build: npm run build
          start: npm run serve:e2e
          wait-on: 'http://localhost:1234'
    env:
      CI: true

  release:
    if: github.event_name == 'push'
    needs: [unit-tests, e2e-tests]
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup bit.dev
        # https://github.com/teambit/bit/issues/2297
        run: |
          ./node_modules/.bin/bit config set analytics_reporting false
          ./node_modules/.bin/bit config set error_reporting false
          ./node_modules/.bin/bit config set user.token $BIT_TOKEN
          ./node_modules/.bin/bit config
          ./node_modules/.bin/bit import -c bit.envs/compilers/react-typescript@3.1.54
          ./node_modules/.bin/bit -v && ./node_modules/.bin/bit import
          ./node_modules/.bin/bit status
        env:
          BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
