name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Run linting
        run: yarn lint

      - name: Run unit tests and generate coverage
        run: yarn test --ci --coverage

      - name: Pack build
        run: yarn pack -o use-debouncy-pack.tgz

      - name: Install packed package
        run: npm install ../use-debouncy-pack.tgz
        working-directory: test-publish

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            lib
            use-debouncy-pack.tgz

  release:
    if: github.event_name == 'push'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
