name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pack-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM
        run: |
          npm install -g npm@8
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack build
        run: echo "pack_name=$(npm pack | tail -n 1)" >> $GITHUB_ENV

      - name: Pack tests
        run: |
          cp ./${{ env.pack_name }} ./test-publish
          cd ./test-publish
          npm install ./${{ env.pack_name }}

    env:
      CI: true

  stryker-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM
        run: |
          npm install -g npm@8
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Stryker tests
        run: npm run stryker

    env:
      CI: true

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM
        run: |
          npm install -g npm@8
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Unit tests
        run: npm run test -- --ci --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
    env:
      CI: true

  release:
    if: github.event_name == 'push'
    needs: [unit-tests]
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM
        run: |
          npm install -g npm@8
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.node-version }}
          path: |
            lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
