name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Run linting
        run: yarn lint

      - name: Run unit tests and generate coverage
        run: yarn test --ci --coverage

      - name: Pack build
        run: yarn pack -o use-debouncy-pack.tgz

      - name: Install packed package
        run: npm install ../use-debouncy-pack.tgz
        working-directory: test-publish

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            lib
            use-debouncy-pack.tgz

  release:
    if: github.event_name == 'push'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_BOT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: npm credentials
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: yarn credentials
        run: yarn config set npmAuthToken $NPM_TOKEN

      - name: Whoiam
        run: yarn npm whoami --publish

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            lib

      - name: Release
        run: yarn release --ci --npm.yarn
